#!/usr/bin/env bash
#!/bin/bash -xv
project_path=$1
if [ -z ${1+x} ] || [ -z "$1" ]; then
  echo 'Please specify a project path'
  exit 0
elif [ ! -d $project_path ]; then
  echo "$project_path is not exists or is not directory"
  exit 0
fi
files=(hook_shares post-checkout post-merge)
for hook in "${files[@]}"
do
  chmod +x $PWD/${hook}
  ln -sf $PWD/${hook} $project_path/.git/hooks/$hook
done

echo "Done ..."
