#!/usr/bin/env bash
#!/bin/bash -xv

# Skip hook
[ -n "$SKIP" ] && exit 0

# fonts
BOLD='\033[1m'
NONE='\033[00m'
PURPLE='\033[01;35m'

project_dir=$(git rev-parse --show-toplevel)
repo_paths=($(cat Gemfile | grep -Po "^gem.*path\s*[:=>]+\s+['\"].*['\"]" | grep -Po "['\"][a-zA-Z0-9_./]+['\"]$" | grep -Po "[a-zA-Z0-9_./]+" | uniq))

# left_branch=$(git rev-parse --abbrev-ref HEAD)
## check if previous commend success
# if [ $? -eq 0 ]; then
#   echo "$repo_dir switched to  $left_branch"
# else
#   echo FAIL
# fi
# echo "done ------------------------------------------------------------"

## check if current repo is clean
# [[ -z $(git status -uno --porcelain) ]] is clean
