#!/usr/bin/env bash
if [ -z ${1+x} ] || [ -z "$1" ]; then
  >&2 echo 'Please specify a project path'
  exit 0
elif [ ! -d $1 ]; then
  >&2 echo "$1 is not exists or is not directory"
  exit 0
elif [ ! -d $1/.git ]; then
  >&2 echo "$1 is not a git repository"
  exit 0
fi
files=(hook_shares post-checkout post-merge)
for hook in "${files[@]}"; do
  chmod +x $PWD/${hook}
  ln -sf $PWD/${hook} $1/.git/hooks/$hook
done

echo "Done ..."
